<?php

namespace DoctrineProxies\__CG__\App\Models\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Models\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entity\\User' . "\0" . 'id', '' . "\0" . 'App\\Models\\Entity\\User' . "\0" . 'email', '' . "\0" . 'App\\Models\\Entity\\User' . "\0" . 'password', '' . "\0" . 'App\\Models\\Entity\\User' . "\0" . 'tfaToken', '' . "\0" . 'App\\Models\\Entity\\User' . "\0" . 'activationToken', '' . "\0" . 'App\\Models\\Entity\\User' . "\0" . 'recoveryToken', '' . "\0" . 'App\\Models\\Entity\\User' . "\0" . 'affiliate', '' . "\0" . 'App\\Models\\Entity\\User' . "\0" . 'dateCreated', '' . "\0" . 'App\\Models\\Entity\\User' . "\0" . 'lastLogin', '' . "\0" . 'App\\Models\\Entity\\User' . "\0" . 'dateRemove', '' . "\0" . 'App\\Models\\Entity\\User' . "\0" . 'active'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entity\\User' . "\0" . 'id', '' . "\0" . 'App\\Models\\Entity\\User' . "\0" . 'email', '' . "\0" . 'App\\Models\\Entity\\User' . "\0" . 'password', '' . "\0" . 'App\\Models\\Entity\\User' . "\0" . 'tfaToken', '' . "\0" . 'App\\Models\\Entity\\User' . "\0" . 'activationToken', '' . "\0" . 'App\\Models\\Entity\\User' . "\0" . 'recoveryToken', '' . "\0" . 'App\\Models\\Entity\\User' . "\0" . 'affiliate', '' . "\0" . 'App\\Models\\Entity\\User' . "\0" . 'dateCreated', '' . "\0" . 'App\\Models\\Entity\\User' . "\0" . 'lastLogin', '' . "\0" . 'App\\Models\\Entity\\User' . "\0" . 'dateRemove', '' . "\0" . 'App\\Models\\Entity\\User' . "\0" . 'active'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setTfaToken($tfaToken = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTfaToken', [$tfaToken]);

        return parent::setTfaToken($tfaToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getTfaToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTfaToken', []);

        return parent::getTfaToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivationToken($activationToken = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivationToken', [$activationToken]);

        return parent::setActivationToken($activationToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivationToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivationToken', []);

        return parent::getActivationToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecoveryToken($recoveryToken = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecoveryToken', [$recoveryToken]);

        return parent::setRecoveryToken($recoveryToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecoveryToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecoveryToken', []);

        return parent::getRecoveryToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setAffiliate($affiliate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAffiliate', [$affiliate]);

        return parent::setAffiliate($affiliate);
    }

    /**
     * {@inheritDoc}
     */
    public function getAffiliate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAffiliate', []);

        return parent::getAffiliate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreated($dateCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreated', [$dateCreated]);

        return parent::setDateCreated($dateCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreated', []);

        return parent::getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastLogin($lastLogin = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastLogin', [$lastLogin]);

        return parent::setLastLogin($lastLogin);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastLogin', []);

        return parent::getLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateRemove($dateRemove = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateRemove', [$dateRemove]);

        return parent::setDateRemove($dateRemove);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateRemove()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateRemove', []);

        return parent::getDateRemove();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

}
