<?php

namespace DoctrineProxies\__CG__\App\Models\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SocialNetworkPlan extends \App\Models\Entity\SocialNetworkPlan implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'id', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'name', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'price', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'duration', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'offer', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'permitLikes', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'permitShares', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'permitFollows', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'likes', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'shares', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'targets', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'trackings', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'processes', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'dateCreated', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'dateModified', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'active', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'socialNetwork'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'id', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'name', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'price', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'duration', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'offer', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'permitLikes', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'permitShares', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'permitFollows', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'likes', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'shares', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'targets', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'trackings', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'processes', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'dateCreated', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'dateModified', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'active', '' . "\0" . 'App\\Models\\Entity\\SocialNetworkPlan' . "\0" . 'socialNetwork'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SocialNetworkPlan $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuration($duration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuration', [$duration]);

        return parent::setDuration($duration);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuration', []);

        return parent::getDuration();
    }

    /**
     * {@inheritDoc}
     */
    public function setOffer($offer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOffer', [$offer]);

        return parent::setOffer($offer);
    }

    /**
     * {@inheritDoc}
     */
    public function getOffer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffer', []);

        return parent::getOffer();
    }

    /**
     * {@inheritDoc}
     */
    public function setPermitLikes($permitLikes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPermitLikes', [$permitLikes]);

        return parent::setPermitLikes($permitLikes);
    }

    /**
     * {@inheritDoc}
     */
    public function getPermitLikes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermitLikes', []);

        return parent::getPermitLikes();
    }

    /**
     * {@inheritDoc}
     */
    public function setPermitShares($permitShares)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPermitShares', [$permitShares]);

        return parent::setPermitShares($permitShares);
    }

    /**
     * {@inheritDoc}
     */
    public function getPermitShares()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermitShares', []);

        return parent::getPermitShares();
    }

    /**
     * {@inheritDoc}
     */
    public function setPermitFollows($permitFollows)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPermitFollows', [$permitFollows]);

        return parent::setPermitFollows($permitFollows);
    }

    /**
     * {@inheritDoc}
     */
    public function getPermitFollows()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermitFollows', []);

        return parent::getPermitFollows();
    }

    /**
     * {@inheritDoc}
     */
    public function setLikes($likes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLikes', [$likes]);

        return parent::setLikes($likes);
    }

    /**
     * {@inheritDoc}
     */
    public function getLikes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLikes', []);

        return parent::getLikes();
    }

    /**
     * {@inheritDoc}
     */
    public function setShares($shares)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShares', [$shares]);

        return parent::setShares($shares);
    }

    /**
     * {@inheritDoc}
     */
    public function getShares()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShares', []);

        return parent::getShares();
    }

    /**
     * {@inheritDoc}
     */
    public function setTargets($targets)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTargets', [$targets]);

        return parent::setTargets($targets);
    }

    /**
     * {@inheritDoc}
     */
    public function getTargets()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTargets', []);

        return parent::getTargets();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrackings($trackings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrackings', [$trackings]);

        return parent::setTrackings($trackings);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrackings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrackings', []);

        return parent::getTrackings();
    }

    /**
     * {@inheritDoc}
     */
    public function setProcesses($processes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProcesses', [$processes]);

        return parent::setProcesses($processes);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcesses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcesses', []);

        return parent::getProcesses();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreated($dateCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreated', [$dateCreated]);

        return parent::setDateCreated($dateCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreated', []);

        return parent::getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModified($dateModified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModified', [$dateModified]);

        return parent::setDateModified($dateModified);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModified', []);

        return parent::getDateModified();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setSocialNetwork(\App\Models\Entity\SocialNetwork $socialNetwork = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSocialNetwork', [$socialNetwork]);

        return parent::setSocialNetwork($socialNetwork);
    }

    /**
     * {@inheritDoc}
     */
    public function getSocialNetwork()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSocialNetwork', []);

        return parent::getSocialNetwork();
    }

}
