<?php

namespace DoctrineProxies\__CG__\App\Models\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserPayments extends \App\Models\Entity\UserPayments implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entity\\UserPayments' . "\0" . 'id', '' . "\0" . 'App\\Models\\Entity\\UserPayments' . "\0" . 'method', '' . "\0" . 'App\\Models\\Entity\\UserPayments' . "\0" . 'paymentId', '' . "\0" . 'App\\Models\\Entity\\UserPayments' . "\0" . 'price', '' . "\0" . 'App\\Models\\Entity\\UserPayments' . "\0" . 'currencyCode', '' . "\0" . 'App\\Models\\Entity\\UserPayments' . "\0" . 'payerEmail', '' . "\0" . 'App\\Models\\Entity\\UserPayments' . "\0" . 'paymentStatus', '' . "\0" . 'App\\Models\\Entity\\UserPayments' . "\0" . 'dateCreated', '' . "\0" . 'App\\Models\\Entity\\UserPayments' . "\0" . 'user', '' . "\0" . 'App\\Models\\Entity\\UserPayments' . "\0" . 'socialNetworkPlan'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entity\\UserPayments' . "\0" . 'id', '' . "\0" . 'App\\Models\\Entity\\UserPayments' . "\0" . 'method', '' . "\0" . 'App\\Models\\Entity\\UserPayments' . "\0" . 'paymentId', '' . "\0" . 'App\\Models\\Entity\\UserPayments' . "\0" . 'price', '' . "\0" . 'App\\Models\\Entity\\UserPayments' . "\0" . 'currencyCode', '' . "\0" . 'App\\Models\\Entity\\UserPayments' . "\0" . 'payerEmail', '' . "\0" . 'App\\Models\\Entity\\UserPayments' . "\0" . 'paymentStatus', '' . "\0" . 'App\\Models\\Entity\\UserPayments' . "\0" . 'dateCreated', '' . "\0" . 'App\\Models\\Entity\\UserPayments' . "\0" . 'user', '' . "\0" . 'App\\Models\\Entity\\UserPayments' . "\0" . 'socialNetworkPlan'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UserPayments $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMethod($method)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMethod', [$method]);

        return parent::setMethod($method);
    }

    /**
     * {@inheritDoc}
     */
    public function getMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMethod', []);

        return parent::getMethod();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentId($paymentId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentId', [$paymentId]);

        return parent::setPaymentId($paymentId);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentId', []);

        return parent::getPaymentId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrencyCode($currencyCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrencyCode', [$currencyCode]);

        return parent::setCurrencyCode($currencyCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrencyCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrencyCode', []);

        return parent::getCurrencyCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayerEmail($payerEmail = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayerEmail', [$payerEmail]);

        return parent::setPayerEmail($payerEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayerEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayerEmail', []);

        return parent::getPayerEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentStatus($paymentStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentStatus', [$paymentStatus]);

        return parent::setPaymentStatus($paymentStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentStatus', []);

        return parent::getPaymentStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreated($dateCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreated', [$dateCreated]);

        return parent::setDateCreated($dateCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreated', []);

        return parent::getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\App\Models\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setSocialNetworkPlan(\App\Models\Entity\SocialNetworkPlan $socialNetworkPlan = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSocialNetworkPlan', [$socialNetworkPlan]);

        return parent::setSocialNetworkPlan($socialNetworkPlan);
    }

    /**
     * {@inheritDoc}
     */
    public function getSocialNetworkPlan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSocialNetworkPlan', []);

        return parent::getSocialNetworkPlan();
    }

}
